### ISSUE TITLE
LimitToLast with start and end cursors is not working as expected

### ISSUE THREAD

**Issue by shiva-6** [googleapis/java-firestore#1068] opened 2022-10-19 12:35 UTC
While querying with cursors and limiting them, limit api works as expected but limitToLast provides unexpected results. similar inconsistencies are visible in the combination of limitToLast and offset.

**Comment by dconeybe** [comment] 2022-10-19 13:17
Please provide a concrete example.

**Comment by shiva-6** [comment] 2022-10-20 05:51
Query query = locations.orderBy("rating").endBefore(4.1);
In my collection locations, this query returns 31 documents as ordered. Also with limit,
locations.orderBy("rating").endBefore(4.1).limit(3);
I get the top 3 results which is perfect but when I use limitToLast I expect to get the last 3 but I get none, an empty list. Similar thing is happening with all startAt, endAt, endBefore and startAfter API's.

**Comment by dconeybe** [comment] 2022-10-20 16:09
Ok I've reproduced the bug. You have definitely found an issue. I'll post back when I have a fix.

**Comment by dconeybe** [comment] 2022-10-22 01:34
This bug has been fixed by https://github.com/googleapis/java-firestore/pull/1072. It will be included in the next release. Thank you for your bug report!

**Closed** 2022-10-22 01:34 UTC
Labels: type: bug, api: firestore

**Comment by dconeybe** [comment] 2022-10-24 19:53
FYI v3.7.0 has been released with the fix:

https://central.sonatype.dev/artifact/com.google.cloud/google-cloud-firestore/3.7.0 

https://github.com/googleapis/java-firestore/pull/1067

**Comment by partapu** [comment] 2022-10-26 09:40
Hey similar inconsistencies are visible in the combination of  limit & limitTolast

Examples:
query=locations.orderBy("rating").limit(10).limittolast(3); 
My location's collection has 82 records, The above query returns the documents numbered 80,81 and 82. Since we are using the limit(10) along with limittolast(3) it should return 8,9,10 documents.

**Comment by cherylEnkidu** [comment] 2022-10-26 15:05
Hi @partapu ,

The firestore doesn't support use both limit and limitToLast in the same query. They are mutually exclusive. Whatever the last one is that you specify is the one that takes effect. In your case you need to achieve the desired result in two steps.
