### ISSUE TITLE
Firestore - Inconsistent behavior in key addressing

### ISSUE THREAD

**Issue by Pirayya** [googleapis/java-firestore#288] opened 2020-07-08 22:14 UTC
OS Type: Its Java - version 11
Firestore Java SDK version (1.33.0, but I can see that the problem still exists in the code on master)

Using field keys with dots (.), i.e. `my.key: "My value"` is allowed, albeit a bit frowned upon, has inconsistent behavior when creating compared to deleting. It is perfectly fine to create a key with dots but cannot be deleted (unless it exists on the top level of the document).

```json
{
   "my.key": true
}
```
can be removed, but:
```json
{
   "my": {
      "specialized.key": true
   }
}
```
cannot.

That's not all! Using the JavaScript SDK for Firestore, deleting is not a problem.

It is always debatable whether or not to use dots in keys, but I think the inconsistency is something that has to be fixed.

#### Steps to reproduce

1. Create a document like the one above (with specialized.key)
2. Run one of the code blocks below
```java
var updates = Map.of("my.specialized.key", FieldValue.delete());
firestore.collection("myCollection").document("myDocument").update(updates)
```
or
```java
var path = new FieldPath("my", "specialized.key");
firestore.collection("myCollection").document("myDocument").update(path, FieldValue.delete()) // <-- Very similar to JavaScript SDK
```

The first code block will succeed without any change, but the second will result in a failed Precondition.

#### Code example

See steps to reproduce

#### Stack trace

Will fail right here: https://github.com/googleapis/java-firestore/blob/80087a3ee7d1d79c099573aa5b9fb618fdff9cff/google-cloud-firestore/src/main/java/com/google/cloud/firestore/UserDataConverter.java#L101

If you don't have time to fix this issue(? don't know if you regard this as an issue), I can definitely contribute!

Tell me if anything is unclear!

**Comment by Pirayya** [comment] 2020-07-09 09:21
@suraj-qlogic, you have the same issue? Or what is happening?

**Comment by suraj-qlogic** [comment] 2020-07-09 10:52
@Pirayya.Thanks for filling an issue.I am currently investigating on it if found any inconsistent behaviour, then will open PR soon

**Comment by Pirayya** [comment] 2020-07-09 12:47
@suraj-qlogic, I am saying that there is inconsistent behavior in addressing keys, although it might've been implemented like that as deliberately. Do you have an idea of what the 'correct' behavior is? I would like to see someone with authority to make a decision here, rather than just making a PR fixing it one way or the other.

**Comment by suraj-qlogic** [comment] 2020-07-09 13:03
> @suraj-qlogic, I am saying that there is inconsistent behavior in addressing keys, although it might've been implemented like that as deliberately. Do you have an idea of what the 'correct' behavior is? I would like to see someone with authority to make a decision here, rather than just making a PR fixing it one way or the other.

@BenWhitehead  @schmidt-sebastian

**Comment by schmidt-sebastian** [comment] 2020-07-09 18:40
First, I want to point out that the code snippets above to very different things:

```
var updates = Map.of("my.specialized.key", FieldValue.delete());
firestore.collection("myCollection").document("myDocument").update(updates)
```

This deletes the field `{ 'my.specialized.key' : ... }`

```
var path = new FieldPath("my", "specialized.key");
firestore.collection("myCollection").document("myDocument").update(path, FieldValue.delete()) // <-- Very similar to JavaScript SDK
```

This deletes the field `{ 'my' { 'specialized.key' : ...  }}`

That being said, the second code snippet should be supported and should not be rejected.

@suraj-qlogic Is this something you can fix?

**Comment by Pirayya** [comment] 2020-07-09 20:51
@schmidt-sebastian, I just tested creating a JSON structure like:
```json
{
   "users": {
      "Pirayya": {
         "color": "blue"
      }
}
```
And ran the following code (Kotlin)
```kotlin
            val key = "users.Pirayya.color"
            val updates = mapOf(key to FieldValue.delete())
            firestore.collection(collection).document(accountKey).update(updates)
```
And the "color" field inside the object "Pirayya" was removed.

So if the expected behavior is to remove the key `{ 'users.Pirayya.color': { ... } }`, then that doesn't work...

I also think the issue regarding the second code example I showed in the ticket can be fixed by figuring out whether or not to use `append()` here: https://github.com/googleapis/java-firestore/blob/80087a3ee7d1d79c099573aa5b9fb618fdff9cff/google-cloud-firestore/src/main/java/com/google/cloud/firestore/UserDataConverter.java#L163

I believe each segment in `FieldPath` should not be split here. If a string is supplied like `users.Pirayya.color` I would agree that splitting it would be a solution, but not if you use `FieldPath.of()` as input.
https://github.com/googleapis/java-firestore/blob/80087a3ee7d1d79c099573aa5b9fb618fdff9cff/google-cloud-firestore/src/main/java/com/google/cloud/firestore/BasePath.java#L61

**Comment by schmidt-sebastian** [comment] 2020-07-09 21:02
As you stated, string keys are expanded (split on dots):
```'a.b.c' => { a : { b : { c: {..}}}```

Field keys created with FieldPath.of() are not:
```'FieldPath.of('a', 'b.c') => { a : { 'b.c' {..}}```

**Comment by Pirayya** [comment] 2020-07-09 23:03
Ok, sorry, I might've not made myself clear. As a user of the Java Firestore SDK I expect `FieldPath.of('a.b', 'c.d')` to point to the key `'c.d'` inside object `'a.b'` when trying to mutate the object:
 ```
{
   "a.b": {
      "c.d": {
         ... 
      }
}
```
Somewhere along the way, all the keys except the first one is changed. So right before the update is made the FieldPath transforms and points to `'d'` inside object `'c'` inside object `'a.b'`:
```
{
   "a.b": {
      "c": {
         "d": {
            ...
         }
      }
   }
}
```

**Comment by schmidt-sebastian** [comment] 2020-07-09 23:29
Your understanding is correct. This looks like a bug.

**Comment by BenWhitehead** [comment] 2020-07-13 22:48
@suraj-qlogic Any chance you can take a look at a fix for this?

**Comment by suraj-qlogic** [comment] 2020-07-13 23:10
@BenWhitehead ,Yes it's in progress.i have been investigated and found this is happen due to this [code](https://github.com/googleapis/java-firestore/blob/b91c57c4b2d3e92478ceaa1a39d467c40e1344dc/google-cloud-firestore/src/main/java/com/google/cloud/firestore/FieldPath.java#L104).I will open PR as soon as possible.

**Comment by BenWhitehead** [comment] 2020-07-14 16:11
Sounds great, thanks @suraj-qlogic!

**Comment by Pirayya** [comment] 2020-07-15 09:05
@suraj-qlogic @BenWhitehead, sorry, accidentally opened a PR here, closed it immediately though. But I have a suggestion for a fix:
https://github.com/Pirayya/java-firestore/pull/1/commits/d11911e86e8fc603ff2049f3fb6014007ec7b603

What do you think?

**Comment by schmidt-sebastian** [comment] 2020-07-15 17:34
@suraj-qlogic I will look at this in a bit (in a meeting now).

**Comment by schmidt-sebastian** [comment] 2020-07-15 17:57
So the problem is in UserDataConverter in line 164. To process the nested updated, we call `path.append` with a Map key, which is a String. In the user's case, it is "specialized.key". `append` splits on dots for all input strings, which we don't want to do here since the field keys in an update Map are all individual field paths. 

The "ugly" fix is:

```
diff --git a/google-cloud-firestore/src/main/java/com/google/cloud/firestore/UserDataConverter.java b/google-cloud-firestore/src/main/java/com/google/cloud/firestore/UserDataConverter.java
index 2b08a12..844f097 100644
--- a/google-cloud-firestore/src/main/java/com/google/cloud/firestore/UserDataConverter.java
+++ b/google-cloud-firestore/src/main/java/com/google/cloud/firestore/UserDataConverter.java
@@ -18,6 +18,7 @@ package com.google.cloud.firestore;
 
 import com.google.cloud.Timestamp;
 import com.google.common.base.Preconditions;
+import com.google.common.collect.ImmutableList;
 import com.google.firestore.v1.ArrayValue;
 import com.google.firestore.v1.MapValue;
 import com.google.firestore.v1.Value;
@@ -160,7 +161,7 @@ class UserDataConverter {
       Map<String, Object> map = (Map<String, Object>) sanitizedObject;
 
       for (Map.Entry<String, Object> entry : map.entrySet()) {
-        Value encodedValue = encodeValue(path.append(entry.getKey()), entry.getValue(), options);
+        Value encodedValue = encodeValue(path.append(new AutoValue_FieldPath(ImmutableList.of(entry.getKey()))), entry.getValue(), options);
         if (encodedValue != null) {
           res.putFields(entry.getKey(), encodedValue);
         }
```

We should find a way to make this pretty.

**Comment by Pirayya** [comment] 2020-07-15 22:29
@schmidt-sebastian, the fix I made in the forked project has another - well, maybe not so beautiful - fix but it is another suggestion. But as I've stated before, I know too little of the intricacies of this project to know all the paths in to encodeValue so I don't know if my proposed fix would be useful. Although if you thought it to be good, instead of me spending a lot of time signing the CLA, getting to know what tests to fix/add etc. maybe someone else can copy it and create a real PR? :P (Sorry for being lazy)

**Comment by schmidt-sebastian** [comment] 2020-07-15 22:55
@Pirayya Sorry, I missed the link to the fork in the earlier comment. Yours is a much cleaner version of what I have. @suraj-qlogic Can we take https://github.com/Pirayya/java-firestore/commit/167443c88e1d33a02ce93882559d368b03ece5e9 and add a test?

**Comment by Pirayya** [comment] 2020-07-15 23:20
@schmidt-sebastian, no problem! But all credit should go to @dmitry-fa, he came with a better suggestion than my first one! 👍

**Comment by suraj-qlogic** [comment] 2020-07-16 02:32
@schmidt-sebastian ,Ok i will do that.

**Closed** 2020-07-16 19:07 UTC
Labels: :rotating_light:, api: firestore, priority: p1, type: bug

**Comment by BenWhitehead** [comment] 2020-07-16 19:09
@schmidt-sebastian Is there anything else we need to address this issue other than what was merged in #295? If not I'll plan on performing a release with this fix early next week.

**Comment by schmidt-sebastian** [comment] 2020-07-16 20:24
No - we are good to go.

**Comment by Pirayya** [comment] 2020-07-17 06:54
Nice, thank you all for helping me solve this so quickly! :) @BenWhitehead, @schmidt-sebastian, @suraj-qlogic and @dmitry-fa!
